### PR TITLE
Test correction, Archive cmd prepa, Participant features

### PR DESCRIPTION
**Pull request by guillain**
* Test correction: content=* removed
* * test_input.py
* * test_menu.py
* Archiving command preparation
* Bot and CiscoSpark with additionnal actions

### CODE REVIEW

**Comment by guillain** [comment]
All tests are validated:
```bash
Ran 357 tests in 43.841s
OK
```

+ del participants features and test

**Comment by guillain** [comment]
Fix input command

**Comment by bernard357** [comment]
Guillain, it is great to have the `make test` command passing all tests. However, it is also important to ensure that Travis-CI tests performed on-line are also successful. These tests are equivalent to the `make test`, but performed on fresh servers on the internet, and done against python 2 and python 3. So results of Travis-CI can be checked directly from the issue page on GitHub itself. Can you please merge changes from the main repo to your repo so that conflicts are resolved? Then we can look specifically at what Travis-CI is reporting on your next commits. Thanks

**Comment by guillain** [comment]
Merge correction

**Comment by guillain** [comment]
Self correction

**Comment by guillain** [comment]
Fix test issues

**Comment by guillain** [comment]
fix int test issues

**Comment by guillain** [comment]
Fix test issues

**Comment by guillain** [comment]
Test in make test ok but not in travis. new check...

**Comment by bernard357** [comment]
Guillain, functions `del_participants` and `del_participant` have been renamed `remove_participants` and `remove_participant` respectively.

**Pull request merged**
